"use client";
import {useState} from "react";
import Link from "next/link";

const tasks=[
{place:"Experimentiertisch",tag:"BEOBACHTUNG",clue:"Ein sauberer Eisennagel wird in eine blaue Kupfersulfatlösung gestellt. Nach einiger Zeit bildet sich auf dem Nagel ein rötlich-brauner Belag.",visual:"Eisennagel  +  CuSO₄(aq)",q:"Welche Beobachtung ist der deutlichste Hinweis darauf, dass ein neuer Stoff entstanden ist?",a:["Das Becherglas besteht aus Glas.","Der Nagel ist fest.","Es bildet sich ein rötlich-brauner Belag.","Die Lösung ist flüssig."],c:2,e:"Der neue rötlich-braune Belag besteht aus metallischem Kupfer.",f:null},
{place:"Teilchenschrank",tag:"ATOM → ION",clue:"Ein neutrales Eisenatom besitzt gleich viele Protonen wie Elektronen. Bei der Reaktion wird daraus ein Fe²⁺-Ion.",visual:"Fe  →  Fe²⁺ + ?",q:"Was passiert, wenn aus einem Eisenatom ein Fe²⁺-Ion wird?",a:["Es nimmt zwei Protonen auf.","Es nimmt zwei Elektronen auf.","Es gibt zwei Neutronen ab.","Es gibt zwei Elektronen ab."],c:3,e:"Das Eisenatom gibt zwei Elektronen ab: Fe → Fe²⁺ + 2 e⁻.",f:"Fe"},
{place:"Blaue Lösung",tag:"IONEN",clue:"Kupfersulfatlösung enthält Cu²⁺-Ionen und SO₄²⁻-Ionen.",visual:"Cu²⁺     SO₄²⁻",q:"Welches Teilchen ist positiv geladen?",a:["SO₄²⁻","Cu²⁺","Ein Elektron","Beide Ionen"],c:1,e:"Cu²⁺ ist das positiv geladene Kupfer-Ion.",f:null},
{place:"Elektronenschloss",tag:"OXIDATION",clue:"Eisenatome an der Oberfläche des Nagels geben Elektronen ab und gehen als Fe²⁺-Ionen in Lösung.",visual:"Fe  →  Fe²⁺ + 2 e⁻",q:"Wie wird dieser Vorgang bezeichnet?",a:["Reduktion","Neutralisation","Oxidation","Schmelzen"],c:2,e:"Oxidation bedeutet Elektronenabgabe. Eisen wird oxidiert.",f:"S"},
{place:"Kupferschloss",tag:"REDUKTION",clue:"Kupfer-Ionen nehmen die Elektronen auf, die vom Eisen abgegeben werden.",visual:"Cu²⁺ + 2 e⁻  →  Cu",q:"Was passiert mit den Cu²⁺-Ionen?",a:["Sie nehmen zwei Elektronen auf.","Sie geben zwei Elektronen ab.","Sie werden zu Sulfat-Ionen.","Sie werden zu Eisen-Ionen."],c:0,e:"Cu²⁺ nimmt zwei Elektronen auf und wird zu neutralem Kupfer. Das ist eine Reduktion.",f:"O"},
{place:"Redox-Tür",tag:"REDOX",clue:"Eisen gibt Elektronen ab, während Kupfer-Ionen sie aufnehmen. Beide Vorgänge laufen gleichzeitig ab.",visual:"Fe → Fe²⁺ + 2e⁻   |   Cu²⁺ + 2e⁻ → Cu",q:"Warum handelt es sich um eine Redoxreaktion?",a:["Weil Sauerstoff vorhanden sein muss.","Weil die Lösung blau ist.","Weil nur eine Oxidation stattfindet.","Weil Oxidation und Reduktion gleichzeitig ablaufen."],c:3,e:"Bei einer Redoxreaktion laufen Reduktion und Oxidation gekoppelt ab. Dabei werden Elektronen übertragen.",f:null},
{place:"Regal der Zuschauer-Ionen",tag:"SULFAT",clue:"Sulfat-Ionen sind vor und nach der Elektronenübertragung vorhanden.",visual:"Cu²⁺ + SO₄²⁻  →  Fe²⁺ + SO₄²⁻",q:"Welches Ion nimmt nicht direkt an der Elektronenübertragung teil?",a:["Fe²⁺","SO₄²⁻","Cu²⁺","Kein Ion"],c:1,e:"SO₄²⁻ bleibt in der Lösung und nimmt weder Elektronen auf noch gibt es Elektronen ab.",f:"4"},
{place:"Formel-Tresor",tag:"FORMEL",clue:"Nach der Reaktion befinden sich Fe²⁺- und SO₄²⁻-Ionen in der Lösung. Die Verbindung muss insgesamt elektrisch neutral sein.",visual:"Fe²⁺ + SO₄²⁻  →  ?",q:"Welche Formel beschreibt Eisen(II)-sulfat?",a:["Fe₂SO₄","FeSO₂","Fe₂(SO₄)₃","FeSO₄"],c:3,e:"Die Ladungen +2 und −2 gleichen sich im Verhältnis 1:1 aus: FeSO₄.",f:null},
{place:"Produktschublade",tag:"PRODUKT",clue:"Der rötlich-braune Belag besteht aus Teilchen, die entstehen, wenn Cu²⁺-Ionen Elektronen aufnehmen.",visual:"Cu²⁺ + 2 e⁻  →  ?",q:"Welcher Stoff scheidet sich auf dem Eisennagel ab?",a:["Kupfer","Eisen","Schwefel","Eisensulfat"],c:0,e:"Cu²⁺-Ionen werden zu metallischen Kupferatomen reduziert.",f:"Cu"},
{place:"Ausgangstür",tag:"FINALES SCHLOSS",clue:"Rekonstruiere die Produkte der Reaktion, um den Fachraum zu verlassen.",visual:"Fe + CuSO₄  →  ?",q:"Welche Produkte vervollständigen die Reaktionsgleichung?",a:["FeCu + SO₄","CuSO₄ + Fe","FeSO₄ + Cu","Fe₂O₃ + Cu"],c:2,e:"Richtig: Fe + CuSO₄ → FeSO₄ + Cu.",f:null}
];

export default function ChemistryEscape(){
 const [i,setI]=useState(0),[sel,setSel]=useState(null),[answered,setAnswered]=useState(false),[frags,setFrags]=useState([]),[done,setDone]=useState(false);
 const t=tasks[i], ok=sel===t.c;
 function choose(x){if(answered)return;setSel(x);setAnswered(true);if(x===t.c&&t.f)setFrags(v=>v.includes(t.f)?v:[...v,t.f]);}
 function next(){if(i===tasks.length-1){setDone(true);return;}setI(i+1);setSel(null);setAnswered(false);}
 if(done)return <div className="chem"><style jsx>{css}</style><div className="finish"><div className="badge">ESCAPE GESCHAFFT</div><h1>🔓 Fachraum entsperrt!</h1><p>You solved all 10 chemistry locks.</p><div className="final">FeSO₄ + Cu</div><h2>What happened?</h2><div className="explain"><b>Oxidation:</b> Fe → Fe²⁺ + 2 e⁻<br/><b>Reduction:</b> Cu²⁺ + 2 e⁻ → Cu<br/><b>Overall reaction:</b> Fe + CuSO₄ → FeSO₄ + Cu<p>Iron atoms transfer electrons to copper ions. Iron is oxidised and copper ions are reduced. The reddish-brown coating is metallic copper; iron(II) sulfate remains in solution.</p></div><div className="actions"><button onClick={()=>location.reload()}>Noch einmal spielen</button><Link href="/"><button className="dark">Zurück zu CityQuest</button></Link></div></div></div>;
 return <div className="chem"><style jsx>{css}</style><header><div><b>⚗ CHEMIE-FACHRAUM ESCAPE</b><small>Iron nail in copper sulfate solution</small></div><div className="prog">SCHLOSS {i+1} / 10<div className="bar"><i style={{width:`${(i+1)*10}%`}}/></div></div></header><main><aside><h4>ESCAPE-ROUTE DURCH DEN FACHRAUM</h4>{tasks.map((x,n)=><div className={`route ${n===i?"now":""} ${n<i?"passed":""}`} key={n}><span>{n<i?"✓":n+1}</span>{x.place}</div>)}<h4 className="recover">GEFUNDENE FRAGMENTE</h4><div className="frags">{["Fe","S","O","4","Cu"].map(x=><b key={x}>{frags.includes(x)?x:"?"}</b>)}</div></aside><section><div className="meta"><b>{t.tag}</b><span>SCHLOSS {i+1}</span></div><h1>{t.place}</h1><div className="evidence"><small>HINWEIS GEFUNDEN</small><div className="visual">{t.visual}</div><p>{t.clue}</p></div><h3>{t.q}</h3><div className="answers">{t.a.map((x,n)=><button key={x} onClick={()=>choose(n)} className={`${answered&&n===t.c?"right":""} ${answered&&sel===n&&n!==t.c?"wrong":""}`}><i>{String.fromCharCode(65+n)}</i>{x}</button>)}</div>{answered&&<div className={`feedback ${ok?"good":"bad"}`}><b>{ok?"Schloss geöffnet.":"Falsche Lösung."}</b><p>{t.e}</p>{ok&&t.f&&<strong>Gefundenes Fragment: {t.f}</strong>}{!ok&&<button onClick={()=>{setSel(null);setAnswered(false)}}>Erneut versuchen</button>}</div>}{answered&&ok&&<button className="next" onClick={next}>{i===9?"Fachraum verlassen":"Weiter zum nächsten Schloss"}</button>}</section></main></div>
}

const css=`
.chem{min-height:100vh;background:#08131c;color:#eef6f8;font-family:inherit;padding-bottom:50px}
header{display:flex;justify-content:space-between;align-items:center;padding:18px 28px;background:#0b1922;border-bottom:1px solid #29414d} header small{display:block;color:#91a9b4;margin-top:4px}.prog{text-align:right;font-weight:800;min-width:180px}.bar{height:7px;background:#1d3440;border-radius:10px;margin-top:7px;overflow:hidden}.bar i{display:block;height:100%;background:#f2d35e}
main{max-width:1180px;margin:auto;padding:28px 18px;display:grid;grid-template-columns:270px 1fr;gap:22px}aside,section,.finish{background:#10222d;border:1px solid #29414d;border-radius:20px;box-shadow:0 18px 55px #0004}aside{padding:20px;align-self:start}h4{color:#82e7d5;font-size:12px;letter-spacing:.1em}.route{display:flex;align-items:center;gap:9px;padding:7px 0;color:#8299a4;font-size:14px}.route span{display:grid;place-items:center;width:25px;height:25px;border-radius:50%;background:#18303c}.route.now{color:white;font-weight:800}.route.passed{color:#82e7d5}.recover{border-top:1px solid #29414d;padding-top:18px}.frags{display:flex;gap:6px;flex-wrap:wrap}.frags b{background:#071016;color:#f2d35e;padding:8px;border-radius:8px;min-width:25px;text-align:center}
section{padding:28px}.meta{display:flex;justify-content:space-between;color:#8da5b0;font-size:12px;letter-spacing:.08em}.meta b{color:#f2d35e}.evidence{background:linear-gradient(135deg,#0a171f,#142b36);border:1px solid #35515e;border-radius:16px;padding:20px;margin:18px 0}.evidence small{color:#82e7d5;font-weight:900;letter-spacing:.1em}.visual{background:#071016;color:#f2d35e;text-align:center;padding:18px;border-radius:12px;margin:14px 0;font-size:clamp(20px,3vw,30px);font-family:monospace}
.answers{display:grid;grid-template-columns:1fr 1fr;gap:11px}.answers button{background:#0b1922;color:white;border:1px solid #35515e;border-radius:12px;padding:14px;text-align:left;font-weight:700;cursor:pointer}.answers i{font-style:normal;display:inline-grid;place-items:center;background:#203844;width:27px;height:27px;border-radius:7px;margin-right:9px}.answers .right{background:#103529;border-color:#56d6a8}.answers .wrong{background:#3b1d22;border-color:#e47777}.feedback{margin-top:17px;padding:15px;border-radius:12px}.feedback p{margin:6px 0}.good{background:#103529;border:1px solid #2e765d}.bad{background:#3b1d22;border:1px solid #7d3b45}.feedback strong{display:block;color:#f2d35e;margin-top:8px}.feedback button,.next,.actions button{border:0;border-radius:10px;padding:11px 15px;font-weight:900;cursor:pointer}.feedback button{margin-top:8px}.next{margin-top:14px;background:#f2d35e;color:#111}
.finish{max-width:820px;margin:50px auto;padding:38px;text-align:center}.badge{display:inline-block;color:#82e7d5;background:#173947;border-radius:99px;padding:7px 12px;font-size:12px;font-weight:900;letter-spacing:.08em}.final{background:#071016;color:#f2d35e;border:1px solid #35515e;border-radius:16px;padding:22px;margin:24px 0;font-size:clamp(32px,6vw,54px);font-weight:900}.explain{text-align:left;max-width:650px;margin:auto;line-height:1.7}.actions{display:flex;justify-content:center;gap:10px;margin-top:25px}.actions button{background:#f2d35e}.actions .dark{background:#18303c;color:white}
@media(max-width:780px){main{grid-template-columns:1fr}aside{display:none}.answers{grid-template-columns:1fr}header{padding:15px}.prog{min-width:120px}}
`;
