"use client";
import {useState} from "react";
import Link from "next/link";

const tasks=[
{place:"Experiment Bench",tag:"OBSERVATION",clue:"A clean iron nail is placed in blue copper sulfate solution. After some time, a reddish-brown coating appears on the nail.",visual:"Fe nail  +  CuSO₄(aq)",q:"Which observation is the clearest evidence that a new substance has formed?",a:["The beaker is made of glass.","The nail is solid.","A reddish-brown coating forms.","The solution is liquid."],c:2,e:"The new reddish-brown coating is metallic copper.",f:null},
{place:"Particle Cabinet",tag:"ATOM → ION",clue:"A neutral iron atom has equal numbers of protons and electrons. During the reaction it becomes Fe²⁺.",visual:"Fe  →  Fe²⁺ + ?",q:"What happens when an iron atom becomes Fe²⁺?",a:["It gains two protons.","It gains two electrons.","It loses two neutrons.","It loses two electrons."],c:3,e:"The iron atom loses two electrons: Fe → Fe²⁺ + 2 e⁻.",f:"Fe"},
{place:"Blue Solution",tag:"IONS",clue:"Copper sulfate solution contains Cu²⁺ ions and SO₄²⁻ ions.",visual:"Cu²⁺     SO₄²⁻",q:"Which particle is positively charged?",a:["SO₄²⁻","Cu²⁺","An electron","Both ions"],c:1,e:"Cu²⁺ is the positively charged copper ion.",f:null},
{place:"Electron Lock",tag:"OXIDATION",clue:"Iron atoms at the nail surface release electrons and enter the solution as Fe²⁺ ions.",visual:"Fe  →  Fe²⁺ + 2 e⁻",q:"How is this process described?",a:["Reduction","Neutralisation","Oxidation","Melting"],c:2,e:"Oxidation means loss of electrons. Iron is oxidised.",f:"S"},
{place:"Copper Lock",tag:"REDUCTION",clue:"Copper ions receive the electrons released by iron.",visual:"Cu²⁺ + 2 e⁻  →  Cu",q:"What happens to the Cu²⁺ ions?",a:["They gain two electrons.","They lose two electrons.","They become sulfate ions.","They become iron ions."],c:0,e:"Cu²⁺ gains two electrons and becomes neutral copper. This is reduction.",f:"O"},
{place:"Redox Door",tag:"REDOX",clue:"Iron loses electrons while copper ions gain them. Both processes happen together.",visual:"Fe → Fe²⁺ + 2e⁻   |   Cu²⁺ + 2e⁻ → Cu",q:"Why is this a redox reaction?",a:["Because oxygen must be present.","Because the solution is blue.","Because only oxidation occurs.","Because oxidation and reduction occur together."],c:3,e:"Redox combines reduction and oxidation. Electrons are transferred.",f:null},
{place:"Spectator Shelf",tag:"SULFATE",clue:"Sulfate ions are present before and after the electron transfer.",visual:"Cu²⁺ + SO₄²⁻  →  Fe²⁺ + SO₄²⁻",q:"Which ion does not directly take part in the electron transfer?",a:["Fe²⁺","SO₄²⁻","Cu²⁺","No ion"],c:1,e:"SO₄²⁻ remains in solution and does not gain or lose electrons.",f:"4"},
{place:"Formula Safe",tag:"FORMULA",clue:"After the reaction, Fe²⁺ and SO₄²⁻ are present in the solution. The compound must be electrically neutral.",visual:"Fe²⁺ + SO₄²⁻  →  ?",q:"Which formula represents iron(II) sulfate?",a:["Fe₂SO₄","FeSO₂","Fe₂(SO₄)₃","FeSO₄"],c:3,e:"The charges +2 and −2 balance in a 1:1 ratio: FeSO₄.",f:null},
{place:"Product Drawer",tag:"PRODUCT",clue:"The reddish-brown coating consists of particles formed when Cu²⁺ ions gain electrons.",visual:"Cu²⁺ + 2 e⁻  →  ?",q:"Which substance is deposited on the nail?",a:["Copper","Iron","Sulfur","Iron sulfate"],c:0,e:"Cu²⁺ ions are reduced to metallic copper atoms.",f:"Cu"},
{place:"Exit Door",tag:"FINAL LOCK",clue:"Reconstruct the products of the reaction to unlock the laboratory.",visual:"Fe + CuSO₄  →  ?",q:"Which products complete the reaction equation?",a:["FeCu + SO₄","CuSO₄ + Fe","FeSO₄ + Cu","Fe₂O₃ + Cu"],c:2,e:"Correct: Fe + CuSO₄ → FeSO₄ + Cu.",f:null}
];

export default function ChemistryEscape(){
 const [i,setI]=useState(0),[sel,setSel]=useState(null),[answered,setAnswered]=useState(false),[frags,setFrags]=useState([]),[done,setDone]=useState(false);
 const t=tasks[i], ok=sel===t.c;
 function choose(x){if(answered)return;setSel(x);setAnswered(true);if(x===t.c&&t.f)setFrags(v=>v.includes(t.f)?v:[...v,t.f]);}
 function next(){if(i===tasks.length-1){setDone(true);return;}setI(i+1);setSel(null);setAnswered(false);}
 if(done)return <div className="chem"><style jsx>{css}</style><div className="finish"><div className="badge">ESCAPE SUCCESSFUL</div><h1>🔓 Laboratory unlocked!</h1><p>You solved all 10 chemistry locks.</p><div className="final">FeSO₄ + Cu</div><h2>What happened?</h2><div className="explain"><b>Oxidation:</b> Fe → Fe²⁺ + 2 e⁻<br/><b>Reduction:</b> Cu²⁺ + 2 e⁻ → Cu<br/><b>Overall reaction:</b> Fe + CuSO₄ → FeSO₄ + Cu<p>Iron atoms transfer electrons to copper ions. Iron is oxidised and copper ions are reduced. The reddish-brown coating is metallic copper; iron(II) sulfate remains in solution.</p></div><div className="actions"><button onClick={()=>location.reload()}>Play again</button><Link href="/"><button className="dark">Back to CityQuest</button></Link></div></div></div>;
 return <div className="chem"><style jsx>{css}</style><header><div><b>⚗ CHEMISTRY LAB ESCAPE</b><small>Iron nail in copper sulfate solution</small></div><div className="prog">LOCK {i+1} / 10<div className="bar"><i style={{width:`${(i+1)*10}%`}}/></div></div></header><main><aside><h4>LAB ESCAPE ROUTE</h4>{tasks.map((x,n)=><div className={`route ${n===i?"now":""} ${n<i?"passed":""}`} key={n}><span>{n<i?"✓":n+1}</span>{x.place}</div>)}<h4 className="recover">RECOVERED FRAGMENTS</h4><div className="frags">{["Fe","S","O","4","Cu"].map(x=><b key={x}>{frags.includes(x)?x:"?"}</b>)}</div></aside><section><div className="meta"><b>{t.tag}</b><span>LOCK {i+1}</span></div><h1>{t.place}</h1><div className="evidence"><small>EVIDENCE FOUND</small><div className="visual">{t.visual}</div><p>{t.clue}</p></div><h3>{t.q}</h3><div className="answers">{t.a.map((x,n)=><button key={x} onClick={()=>choose(n)} className={`${answered&&n===t.c?"right":""} ${answered&&sel===n&&n!==t.c?"wrong":""}`}><i>{String.fromCharCode(65+n)}</i>{x}</button>)}</div>{answered&&<div className={`feedback ${ok?"good":"bad"}`}><b>{ok?"Lock opened.":"Access denied."}</b><p>{t.e}</p>{ok&&t.f&&<strong>Recovered fragment: {t.f}</strong>}{!ok&&<button onClick={()=>{setSel(null);setAnswered(false)}}>Try again</button>}</div>}{answered&&ok&&<button className="next" onClick={next}>{i===9?"Open laboratory door":"Continue to next lock"}</button>}</section></main></div>
}

const css=`
.chem{min-height:100vh;background:#08131c;color:#eef6f8;font-family:inherit;padding-bottom:50px}
header{display:flex;justify-content:space-between;align-items:center;padding:18px 28px;background:#0b1922;border-bottom:1px solid #29414d} header small{display:block;color:#91a9b4;margin-top:4px}.prog{text-align:right;font-weight:800;min-width:180px}.bar{height:7px;background:#1d3440;border-radius:10px;margin-top:7px;overflow:hidden}.bar i{display:block;height:100%;background:#f2d35e}
main{max-width:1180px;margin:auto;padding:28px 18px;display:grid;grid-template-columns:270px 1fr;gap:22px}aside,section,.finish{background:#10222d;border:1px solid #29414d;border-radius:20px;box-shadow:0 18px 55px #0004}aside{padding:20px;align-self:start}h4{color:#82e7d5;font-size:12px;letter-spacing:.1em}.route{display:flex;align-items:center;gap:9px;padding:7px 0;color:#8299a4;font-size:14px}.route span{display:grid;place-items:center;width:25px;height:25px;border-radius:50%;background:#18303c}.route.now{color:white;font-weight:800}.route.passed{color:#82e7d5}.recover{border-top:1px solid #29414d;padding-top:18px}.frags{display:flex;gap:6px;flex-wrap:wrap}.frags b{background:#071016;color:#f2d35e;padding:8px;border-radius:8px;min-width:25px;text-align:center}
section{padding:28px}.meta{display:flex;justify-content:space-between;color:#8da5b0;font-size:12px;letter-spacing:.08em}.meta b{color:#f2d35e}.evidence{background:linear-gradient(135deg,#0a171f,#142b36);border:1px solid #35515e;border-radius:16px;padding:20px;margin:18px 0}.evidence small{color:#82e7d5;font-weight:900;letter-spacing:.1em}.visual{background:#071016;color:#f2d35e;text-align:center;padding:18px;border-radius:12px;margin:14px 0;font-size:clamp(20px,3vw,30px);font-family:monospace}
.answers{display:grid;grid-template-columns:1fr 1fr;gap:11px}.answers button{background:#0b1922;color:white;border:1px solid #35515e;border-radius:12px;padding:14px;text-align:left;font-weight:700;cursor:pointer}.answers i{font-style:normal;display:inline-grid;place-items:center;background:#203844;width:27px;height:27px;border-radius:7px;margin-right:9px}.answers .right{background:#103529;border-color:#56d6a8}.answers .wrong{background:#3b1d22;border-color:#e47777}.feedback{margin-top:17px;padding:15px;border-radius:12px}.feedback p{margin:6px 0}.good{background:#103529;border:1px solid #2e765d}.bad{background:#3b1d22;border:1px solid #7d3b45}.feedback strong{display:block;color:#f2d35e;margin-top:8px}.feedback button,.next,.actions button{border:0;border-radius:10px;padding:11px 15px;font-weight:900;cursor:pointer}.feedback button{margin-top:8px}.next{margin-top:14px;background:#f2d35e;color:#111}
.finish{max-width:820px;margin:50px auto;padding:38px;text-align:center}.badge{display:inline-block;color:#82e7d5;background:#173947;border-radius:99px;padding:7px 12px;font-size:12px;font-weight:900;letter-spacing:.08em}.final{background:#071016;color:#f2d35e;border:1px solid #35515e;border-radius:16px;padding:22px;margin:24px 0;font-size:clamp(32px,6vw,54px);font-weight:900}.explain{text-align:left;max-width:650px;margin:auto;line-height:1.7}.actions{display:flex;justify-content:center;gap:10px;margin-top:25px}.actions button{background:#f2d35e}.actions .dark{background:#18303c;color:white}
@media(max-width:780px){main{grid-template-columns:1fr}aside{display:none}.answers{grid-template-columns:1fr}header{padding:15px}.prog{min-width:120px}}
`;
