"use client";
import { useMemo, useState } from "react";

const FRAGEN = [
{frage:"Welche Aufgabe haben die Hoden?",antworten:["Sie bilden Spermien und das Hormon Testosteron.","Sie speichern den Urin.","Sie bilden Eizellen.","Sie transportieren Spermien zur Gebärmutter."],richtig:0,tipp:"Denke daran, welche männlichen Keimzellen dort entstehen."},
{frage:"Welche Aufgabe hat die Gebärmutter?",antworten:["Dort reifen Spermien heran.","Dort kann sich eine befruchtete Eizelle einnisten und entwickeln.","Sie produziert Urin.","Sie verbindet die Eierstöcke direkt mit der Scheide."],richtig:1,tipp:"Denke daran, wo sich ein Embryo während einer Schwangerschaft entwickelt."},
{frage:"Was passiert bei der Menstruation?",antworten:["Ein Eierstock wird abgestoßen.","Die Gebärmutterschleimhaut wird teilweise abgestoßen.","Alle Eizellen verlassen gleichzeitig den Körper.","Die Gebärmutter wird vollständig entleert."],richtig:1,tipp:"Im Zyklus baut sich in der Gebärmutter eine Schleimhaut auf."},
{frage:"Was bedeutet Eisprung?",antworten:["Eine Eizelle wird aus einem Eierstock freigesetzt.","Die Menstruation beginnt.","Eine Eizelle nistet sich ein.","Eine Eizelle wird befruchtet."],richtig:0,tipp:"Der Eisprung ist zunächst noch keine Befruchtung."},
{frage:"Warum baut sich die Gebärmutterschleimhaut während des Zyklus auf?",antworten:["Damit mehr Urin gespeichert wird.","Damit sich eine befruchtete Eizelle einnisten könnte.","Damit neue Eierstöcke entstehen.","Damit die Menstruation verhindert wird."],richtig:1,tipp:"Überlege, was nach einer Befruchtung in der Gebärmutter passieren könnte."},
{frage:"Welche Aussage zum Kondom ist richtig?",antworten:["Es verhindert immer den Eisprung.","Es kann eine Schwangerschaft verhindern und schützt zusätzlich vor vielen sexuell übertragbaren Infektionen.","Es wirkt durch Hormone.","Es wird in die Gebärmutter eingesetzt."],richtig:1,tipp:"Das Kondom ist eine mechanische Barriere."},
{frage:"Wie wirkt die Antibabypille hauptsächlich?",antworten:["Hormone können unter anderem den Eisprung verhindern.","Sie tötet Spermien außerhalb des Körpers.","Sie bildet eine Gummibarriere.","Sie entfernt eine befruchtete Eizelle."],richtig:0,tipp:"Denke an die hormonelle Steuerung des weiblichen Zyklus."},
{frage:"Welche Verhütungsmethode kommt ohne Hormone aus?",antworten:["Antibabypille","Hormonring","Kondom","Hormonimplantat"],richtig:2,tipp:"Gesucht ist eine mechanische Verhütungsmethode."},
{frage:"Was ist für die Intimhygiene normalerweise sinnvoll?",antworten:["Mehrmals täglich stark parfümierte Seife verwenden.","Regelmäßig mit Wasser und bei Bedarf milden geeigneten Produkten reinigen.","Den Intimbereich möglichst nie waschen.","Täglich Desinfektionsmittel verwenden."],richtig:1,tipp:"Aggressive oder stark parfümierte Produkte können empfindliche Haut und Schleimhäute reizen."}
];
const LOESUNG="VERHÜTUNG";
function mischen(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];}return x;}
export default function BiologieQuiz(){
 const buchstaben=useMemo(()=>mischen([...LOESUNG]),[]); const [index,setIndex]=useState(0); const [gesammelt,setGesammelt]=useState([]); const [falsche,setFalsche]=useState([]); const [tipp,setTipp]=useState(""); const [eingabe,setEingabe]=useState(""); const [meldung,setMeldung]=useState(""); const [fertig,setFertig]=useState(false); const codefrage=index===FRAGEN.length; const frage=FRAGEN[index];
 function antworten(i){if(!frage||falsche.includes(i))return;if(i===frage.richtig){const b=buchstaben[index];setGesammelt(a=>[...a,b]);setMeldung("Richtig! Dein Buchstabe ist: "+b);setTipp("");setTimeout(()=>{setIndex(a=>a+1);setFalsche([]);setMeldung("");},1000);}else{setFalsche(a=>[...a,i]);setTipp(frage.tipp);setMeldung("Noch nicht richtig. Diese Antwort fällt weg.");}}
 function pruefen(){const x=eingabe.trim().toUpperCase().replaceAll("UE","Ü");if(x===LOESUNG){setFertig(true);setMeldung("");}else setMeldung("Noch nicht richtig. Ordne deine neun Buchstaben neu.");}
 return <main className="seite"><section className="karte"><header><div><div className="fach">Biologie · Klasse 8</div><h1>Escape Quiz: Sexualerziehung II</h1><p>Löse 9 Fachfragen, sammle 9 Buchstaben und knacke am Ende das Lösungswort.</p></div><div className="stand">Frage {Math.min(index+1,10)} / 10</div></header><div className="sammlung"><b>Gesammelte Buchstaben</b><div className="letters">{Array.from({length:9}).map((_,i)=><span key={i}>{gesammelt[i]??"?"}</span>)}</div></div>
 {!codefrage&&!fertig&&<><div className="frage"><small>Frage {index+1}</small><h2>{frage.frage}</h2></div><div className="antworten">{frage.antworten.map((a,i)=><button key={i} disabled={falsche.includes(i)} className={falsche.includes(i)?"weg":""} onClick={()=>antworten(i)}><b>{String.fromCharCode(65+i)}</b><span>{falsche.includes(i)?"Diese Antwort fällt weg.":a}</span></button>)}</div>{meldung&&<div className="meldung">{meldung}</div>}{tipp&&<div className="tipp"><b>Tipp:</b> {tipp}</div>}</>}
 {codefrage&&!fertig&&<div className="finale"><small>Frage 10</small><h2>Wie lautet das Lösungswort?</h2><p>Bringe deine neun Buchstaben in die richtige Reihenfolge.</p><div className="gross">{gesammelt.map((b,i)=><span key={i}>{b}</span>)}</div><input value={eingabe} onChange={e=>setEingabe(e.target.value)} onKeyDown={e=>e.key==="Enter"&&pruefen()} placeholder="Lösungswort"/><button className="pruef" onClick={pruefen}>Code prüfen</button>{meldung&&<div className="meldung">{meldung}</div>}</div>}
 {fertig&&<div className="finale"><div className="dna">🧬</div><h2>Escape geschafft!</h2><p>Das Lösungswort lautet: <b>VERHÜTUNG</b></p><button className="pruef" onClick={()=>location.reload()}>Noch einmal spielen</button></div>}</section><style jsx>{`*{box-sizing:border-box}.seite{min-height:100vh;padding:28px 16px;background:linear-gradient(145deg,#eefbf6,#f5faff);font-family:Arial,sans-serif;color:#17342b}.karte{max-width:900px;margin:auto;background:#fff;border-radius:24px;padding:28px;box-shadow:0 18px 55px #154e3a1f}header{display:flex;justify-content:space-between;gap:20px;border-bottom:2px solid #e3f2ec;padding-bottom:18px}.fach,small{color:#19744f;font-weight:900}.stand{background:#e5f7ef;padding:10px 14px;border-radius:30px;height:max-content;font-weight:bold}h1{font-size:clamp(28px,5vw,44px);margin:5px 0}h2{margin:5px 0;font-size:clamp(22px,4vw,30px)}.sammlung{margin:20px 0;padding:15px;background:#f1faf6;border-radius:16px}.letters,.gross{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.letters span,.gross span{display:grid;place-items:center;width:44px;height:48px;border:2px solid #65ae8d;border-radius:10px;font-size:24px;font-weight:900;background:#fff}.frage{padding:18px;background:#f8fcfa;border-radius:16px;margin-bottom:14px}.antworten{display:grid;gap:11px}.antworten button{display:flex;gap:14px;align-items:center;text-align:left;padding:15px;border:2px solid #d5e9e0;border-radius:14px;background:#fff;font-size:16px;cursor:pointer}.antworten button b{display:grid;place-items:center;min-width:35px;height:35px;border-radius:50%;background:#e4f5ed;color:#176744}.antworten .weg{opacity:.3;text-decoration:line-through;cursor:default}.meldung,.tipp{margin-top:14px;padding:13px;border-radius:12px}.meldung{background:#edf8ff}.tipp{background:#fff8dd}.finale{text-align:center;padding:25px 5px}.gross{justify-content:center;margin:20px}input{display:block;width:min(450px,100%);margin:16px auto 10px;padding:14px;border:2px solid #aad5c2;border-radius:12px;font-size:20px;text-align:center;text-transform:uppercase}.pruef{border:0;border-radius:12px;padding:14px 22px;background:#19744f;color:white;font-size:16px;font-weight:bold;cursor:pointer}.dna{font-size:65px}@media(max-width:650px){.karte{padding:18px}header{flex-direction:column}}`}</style></main>;
}
